### ISSUE TITLE
Create entity and table for header tracking

### ISSUE THREAD

**Issue by JulietteMadi** [Frank-readresolve/itp3-mail-sender#49]

**Comment by JulietteMadi** [comment]
- [ ] Create new branch
- [ ] Create the mail trackers MPD 
- [ ] Add the mail_trackers table in script
- [ ] Add the headers table in script
- [ ] Add the mailTracker entity
- [ ] Add the header entity
